### ISSUE TITLE
Add page up/page down, and prev-diff controls

### ISSUE THREAD

**Issue by jdek** [dwbuiten/bxd#2]
I tried to do this by adapting the [event loop](https://github.com/dwbuiten/bxd/blob/master/main.c#L91-L152), and copying the up/down cases and changing some of the values, it sort of worked, but it would bug out when going back up, this is probably because I don't really understand how movement is actually done, though I guess I just need to look at the code some more.

These would be some really useful controls when diffing files:
`page up` move a whole screen up
`page down` move a whole screen down
`shift-space`? go back to the previous diff

**Comment by dwbuiten** [comment]
I was thinking of `n` and `p` for next and previous, but `shift-space` works too.

Page up/down would be useful too, and not that hard.

Both have been on my TODO, but it's a person side project, and life is life.

Maybe within the next week?
